### ISSUE TITLE
It should respect [ToggleLeft] attribute

### ISSUE THREAD

**Issue by iMobCoding** [Schwapo/SwitchButton#1]
Amazing attribute you made :)
I'd just like if it respected the [ToggleLeft] attribute...

**Comment by schwapo** [comment]
I could add that, but It does have an `Alignment` parameter that you can set to `SwitchAlignment.Left` to get the same result, so I'm unsure if it's worth it. I'd be glad to hear your opinion on it though 😄

**Comment by iMobCoding** [comment]
It's not the same thing, at least in my case... When I set `SwitchAlignment.Left` it still shows the Switch on the `right side` of the label, just aligned to the left. But when I use `[ToggleLeft]` it places the toggle on the `left side` of the label

**Comment by schwapo** [comment]
Right, forgot that toggle left does that. I'll add support for it 😄

**Comment by iMobCoding** [comment]
And small change while you're at the code... It gives `obsolete` warnings so I had to change
`EditorTimeHelper.Time.DeltaTime` to `GUITimeHelper.LayoutDeltaTime` in 3 lines of code :)

**Comment by schwapo** [comment]
The switch now respects the ToggleLeft attribute. I also changed a few names to conform with naming conventions and changed calls to obsolete methods.
